### ISSUE TITLE
Glibc 2.22 support

### ISSUE THREAD

**Issue by felipemogollon** [yanqi27/core_analyzer#1]
Hi, I am trying to run core_analyzer against my application but I am getting this error message:

./core_analyzer -b ./my_application mycore
The memory manager of glibc 2.22 is not supported in this release
Fail to initialize core analyzer

**Comment by yanqi27** [comment]
Could you let me know what OS is on your machine?

**Comment by felipemogollon** [comment]
Debían testing 64 bits (8.0 based)

**Comment by yanqi27** [comment]
The support of memory manager of glibc 2.22 is under development. I will update the project once I test it.

**Comment by felipemogollon** [comment]
Thank you very much

**Comment by yanqi27** [comment]
A fix is updated to support glibc of version up to 2.23. Unfortunately, I don't have an environment to test version later than 2.19. If you can give it a shot, it will be great.

**Comment by felipemogollon** [comment]
Hi, thank you very much for your effort.

I have checked it and it seems to work, but I am getting the following issue:
`./core_analyzer -b myapp mycore
Please input the address of variable main_arena
You can find it by command "(gdb)print &main_arena"
main_arena ? 
Please input the address of variable mp_
You can find it by command "(gdb)print &mp_"
mp_ ? 
Failed to get the addresses of global variables main_arena & mp_
Fail to initialize core analyzer
`

I think I don't know how to use it...

**Comment by yanqi27** [comment]
Hi Felipe,

The tool needs to know the address of two variables belonging to the heap
memory manager, ptmalloc. It is easier if you use the gdb version of the
tool. For a quick start, you may take a look at the project's website
http://core-analyzer.sourceforge.net/

regards,
Michael

**Comment by yanqi27** [comment]
Close the ticket with commit [b8090dc](https://github.com/yanqi27/core_analyzer/commit/b8090dc895fd40842fe0ca00de6caf1e87f6edec)

**Comment by songfeng91** [comment]
> Hi Felipe,
> 
> The tool needs to know the address of two variables belonging to the heap memory manager, ptmalloc. It is easier if you use the gdb version of the tool. For a quick start, you may take a look at the project's website http://core-analyzer.sourceforge.net/
> 
> regards, Michael
> 
> On Wed, Jun 29, 2016 at 10:02 AM, Felipe Mogollón [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Hi, thank you very much for your effort.
> > I have checked it and it seems to work, but I am getting the following
> > issue:
> > ./core_analyzer -b myapp mycore
> > Please input the address of variable main_arena
> > You can find it by command "(gdb)print &main_arena"
> > main_arena ?
> > Please input the address of variable mp_
> > You can find it by command "(gdb)print &mp_"
> > mp_ ?
> > Failed to get the addresses of global variables main_arena & mp_
> > Fail to initialize core analyzer
> > I think I don't know how to use it...
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > [#1 (comment)](https://github.com/yanqi27/core_analyzer/issues/1#issuecomment-229365250),
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AMMgcWAHBbZbrke1komXmbBfhNUqurWqks5qQnsIgaJpZM4IgCUr
> > .

Hi, Michael
As you suggested, using gdb version is easier, but i got the same error for gdb version, is it because that the gdb version only works for ptmalloc? My project is based on jni, so the heap memory is managed by jemalloc, Is there any way for me to solve the problem?
![image](https://user-images.githubusercontent.com/111404230/185020899-020ea00d-7469-4115-947e-cbb3a24b32a5.png)

regards,
songfeng91
