### ISSUE TITLE
Error running core_analyzer_2_16 with redhat 7.0

### ISSUE THREAD

**Issue by tsprasannaa** [yanqi27/core_analyzer#14]
Hi,
Trying to run core_analyzer_2_16 on redhat7.0(maipo). I get the following glibc version error. 
"""
The memory manager of glibc 2.17 is not supported in this release
Fail to initialize core analyzer
"""

Can you let me know if this issue is known/already fixed.
Please let me know if any other information is required.

Thanks

**Comment by tsprasannaa** [comment]
Also tried option to build gdb from source by patching the gdb contents. This resulted in same error.
#0  0x00002b79214b87f9 in __vsyslog_chk () from /lib64/libc.so.6
(gdb) heap
The memory manager of glibc 2.17 is not supported in this release
[Error] Failed to walk heap
(gdb)

More information:
# uname -a
Linux rh 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Can you please advice if I have to use higher versions of core_analyzer to get around this issue?

Thanks,
Prasannaa.

**Comment by yanqi27** [comment]
Hi Prasannaa,

yeah, could you try the higher version? are you using gdb or the command line tool?

thanks,
Michael

**Comment by tsprasannaa** [comment]
Thanks Michael,

I tried with both gdb and the command line tool. I had to recompile the source in both the modes.
However, I will try higher versions as you suggested.

Thanks,
Prasannaa.

**Comment by tsprasannaa** [comment]
I dont see the error anymore using higher version. I could open the core file. However I am not sure if the following error is related to core_analyzer / the core file itself. Can you please help confirming?

(gdb) heap
        Tuning params & stats:
                mmap_threshold=131072
                pagesize=4096
                n_mmaps=3
                n_mmaps_max=65536
                total mmap regions created=3
                mmapped_mem=36220928
                sbrk_base=0x383c000
        Main arena (0x2b7921782760) owns regions:
                [0x1db08900f - 0x1db089000] Total 17179869184.0GB### **Failed to get the first chunk at 0x1db088fff**

        Dynamic arena (0x2b794c000020) owns regions:
                [0x2b794c0008c0 - 0x2b794c65a000] Total 6MB in-use 9098(952KB) free 882(5MB)
        Dynamic arena (0x2b7948000020) owns regions:
                [0x2b79480008c0 - 0x2b79485cc000] Total 5MB in-use 7704(760KB) free 982(4MB)
        Dynamic arena (0x2b7944000020) owns regions:
                [0x2b79440008c0 - 0x2b7944021000] Total 129KB in-use 3(1KB) free 1(128KB)
        Dynamic arena (0x2b7940000020) owns regions:
                [0x2b79400008c0 - 0x2b7940690000] Total 6MB in-use 7500(751KB) free 1165(5MB)
        Dynamic arena (0x2b7934000020) owns regions:
                [0x2b79340008c0 - 0x2b793468e000] Total 6MB in-use 11207(1MB) free 1243(5MB)
        Dynamic arena (0x2b793c000020) owns regions:
                [0x2b793c0008c0 - 0x2b793c598000] Total 5MB in-use 8183(894KB) free 895(4MB)
        Dynamic arena (0x2b7928000020) owns regions:
                [0x2b79280008c0 - 0x2b79286f8000] Total 6MB in-use 9519(988KB) free 956(5MB)
        Dynamic arena (0x2b7924000020) owns regions:
                [0x2b79240008c0 - 0x2b7926c2a000] Total 44MB in-use 113775(37MB) free 1225(6MB)
        mmap-ed large memory blocks:
                [0x178a1010 - 0x1178a1000] Total 4.0GB in-use 1(4.0GB) free 0(0)
                [0x2b791e867010 - 0x2b791e8a6000] Total 251KB in-use 1(251KB) free 0(0)
                [0x2b791e8a6010 - 0x2b791e94f000] Total 675KB in-use 1(675KB) free 0(0)
                [0x2b792d004010 - 0x2b792f1a7000] Total 33MB in-use 1(33MB) free 0(0)
                4 mmap-ed large memory blocks are found, however, 3 is recorded in mp_

**### 1 Errors encountered while walking the heap!
[Error] Failed to walk heap**

**Comment by tsprasannaa** [comment]
Hi Michael,
Could you please comment on the above post. This will be helpful.
Specifically I am looking at solving the following errors.

" Failed to get the first chunk at 0x1db088fff"
1 Errors encountered while walking the heap!
[Error] Failed to walk heap

Thanks,
Prasannaa.

**Comment by tsprasannaa** [comment]
Also, the "heap" command starts with the following errors.

(gdb) heap
Failed to lookup gv "mp_"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"
Failed to lookup gv "main_arena"

Thanks,
Prasannaa.

**Comment by yanqi27** [comment]
Hi Prasannaa,

You need to download libc.so debug symbols (install a package depending on your Linux distro.) That will fix the warning of 
```Failed to lookup gv "mp_"```. core_analyzer depends on these variables to get the right answer.

-Michael

**Comment by yanqi27** [comment]
It is not an issue.

**Comment by juxeii** [comment]
What are u guys referring to here as "higher version"?
Higher RedHat version or higher core_analyzer version?
Getting the same error for the standalone tool.
