### ISSUE TITLE
`xxx.so` is not found

### ISSUE THREAD

**Issue by GoGoYao** [yanqi27/core_analyzer#15]
Hi, I download the whole project and run directly as ` ./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb bin core.17027`. I get `xxx.so not found` error, eg. `./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb: /lib64/libc.so.6: version GLIBC_2.15' not found (required by ./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb)`.
So, is it my environment version not ok? My kernal is as follow, 
`Linux 3.10.0_3-0-0-11 #5 SMP Thu Sep 21 13:16:48 CST 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by GoGoYao** [comment]
> Hi, I download the whole project and run directly as ` ./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb bin core.17027`. I get `xxx.so not found` error, eg. `./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb: /lib64/libc.so.6: version GLIBC_2.15' not found (required by ./core_analyzer/bin/Linux/tcmalloc/gdb-7.11.1/gdb)`.
> So, is it my environment version not ok? My kernal is as follow,
> `Linux 3.10.0_3-0-0-11 #5 SMP Thu Sep 21 13:16:48 CST 2017 x86_64 x86_64 x86_64 GNU/Linux`

I see that `The executables are compiled on Ubuntu 18.04.1 LTS.` and my operation system is centos 6.3. I will compile and try again.

**Comment by yanqi27** [comment]
Yes, my building environment has a different version of libc.so
