### ISSUE TITLE
[compile error]configure: error: python is missing or unusable

### ISSUE THREAD

**Issue by GoGoYao** [yanqi27/core_analyzer#16]
My environment is centos and kernal is `3.10.0_3-0-0-26 #1 SMP Tue Mar 19 16:20:29 CST 2019 x86_64 GNU/Linux`. I download source code of gdb 7.11.1 and compile as follows,
`cd gdb-7.11.1 && cp ../core_analyzer/gdbplus/gdb-7.11.1/gdb/* gdb/ -r && ./configure --with-python --prefix=/usr/local && make -j 20`. Then I encountered error `configure: error: python is missing or unusable`. I can use python in my terminal as follows 
```
gdb-7.11.1 20:18:08 $ python
Python 2.7.3 (default, Mar 28 2019, 15:45:17)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by yanqi27** [comment]
Can you try compiling gdb w/o core_analyzer?
BTW, there is a subfolder under `gdbplus/gdb-7.11.1/gdb/python` which you need to copy as well.

**Comment by GoGoYao** [comment]
> Can you try compiling gdb w/o core_analyzer?
> BTW, there is a subfolder under `gdbplus/gdb-7.11.1/gdb/python` which you need to copy as well.

Sorry I don't understand your reply.
1. What do you mean by `compiling gdb w/o`?
2. What need I copy to `gdbplus/gdb-7.11.1/gdb/python`, the whole python installed package?

**Comment by yanqi27** [comment]
I meant that you can try compile gdb without integrating core_analyzer. Just do a full build.
For the folder gdbplus/gdb-7.11.1/gdb/python, just copy the files under it to the corresponding folder of the gdb source tree.

**Comment by yanqi27** [comment]
It is not an issue.

**Comment by nfranke** [comment]
You need to install python-dev in order to compile. However, with gdb 8.1 on ubuntu 18 gdbplus does not work.

**Comment by wisdomleo** [comment]
@nfranke you are right, it should be missing python-dev.
