### ISSUE TITLE
GDB 8.2 support

### ISSUE THREAD

**Issue by BBBc0927** [yanqi27/core_analyzer#18]
Hi Michael
I failed to build core_analyzer under gdb-8.2.
It seems the failure related to some changed between gdb8.1 and gdb8.2.
Details as follows:
[ 2246s] ../../gdb/python/py-ref.c: In function 'PyObject* object_ref_str(PyObject*)':
[ 2246s] ../../gdb/python/py-ref.c:348:16: error: 'type_name_no_tag' was not declared in this scope
[ 2246s]     if (type && type_name_no_tag(type))
[ 2246s]                 ^~~~~~~~~~~~~~~~
[ 2246s] ../../gdb/python/py-ref.c:348:16: note: suggested alternative: 'type_name'
[ 2246s]     if (type && type_name_no_tag(type))
[ 2246s]                 ^~~~~~~~~~~~~~~~
[ 2246s]                 type_name

After examining ChangeLog of gdb, i found this API has been removed. 
* gdbtypes.c (type_name_no_tag): Remove.
* gdbtypes.h (type_name_no_tag): Remove.

Are there any other methods to solve these problems?

**Comment by yanqi27** [comment]
Hi @BBBc0927 
Since gdb changes internal APIs frequently, core_analyzer doesn't support all gdb versions out of box. If you need a particular gdb version, for instance 8.2, you have to port to that version. It is not difficult, mostly plumbing work.

**Comment by BBBc0927** [comment]
Thanks Michael!
I've ported to that version successfully.

Another problem is core analyzer failed to find symbol "mp_" in gdb8.1, however, gdb could print this value.
Some logs as follows:

(gdb) heap
Failed to lookup gv "mp_"
Failed to extract heap metadata from gv mp_
==================================================================================
== The memory manager is assumed to be glibc 2.26                                ==
== If this is not true, please debug with another machine with matching glibc   ==
==================================================================================
[Error] Failed to walk heap
(gdb) p &mp_
$1 = (<data variable, no debug info> *) 0x7f14e1bb4260 <mp_>

Besides, i've installed some debuginfo related packages.

**Comment by yanqi27** [comment]
core_analyzer needs to know the type of `mp_`. In other words, you should be able to print out the content of the global variable. From the output above, gdb knows the address of `mp_`, but doesn't know its type definition.

**Comment by BBBc0927** [comment]
Thank you Michael.
I think we could close this session now.
