### ISSUE TITLE
Build v2.20 stand alone binary on CentOs 7.8 failed 

### ISSUE THREAD

**Issue by KennyYanXM** [yanqi27/core_analyzer#23]
hi Michael, 

I ran the following command and got error, can you help?

`cd core_analyzer-2.20.0/app/Linux`
`make`

And I got the following error:

make: *** No rule to make target `search.o', needed by `core_analyzer'.  Stop.

BTW, my local gdb version is 7.6.1

**Comment by KennyYanXM** [comment]
I resolved this problem now but there is another issue as following which stop me from building the binary:

=======================
../heap_ptmalloc.cpp: In function ‘int thread_tcache(thread_info*, void*)’:
../heap_ptmalloc.cpp:912:24: error: invalid use of incomplete type ‘struct thread_info’
  switch_to_thread (info->ptid);
                        ^~
../heap_ptmalloc.cpp:902:23: note: forward declaration of ‘struct thread_info’
 thread_tcache (struct thread_info *info, void *data)
                       ^~~~~~~~~~~
../heap_ptmalloc.cpp:912:2: error: ‘switch_to_thread’ was not declared in this scope
  switch_to_thread (info->ptid);
  ^~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:912:2: note: suggested alternative: ‘ca_thread’
  switch_to_thread (info->ptid);
  ^~~~~~~~~~~~~~~~
  ca_thread
../heap_ptmalloc.cpp:914:37: error: ‘VAR_DOMAIN’ was not declared in this scope
  tcsym = lookup_symbol("tcache", 0, VAR_DOMAIN, 0).symbol;
                                     ^~~~~~~~~~
../heap_ptmalloc.cpp:914:37: note: suggested alternative: ‘CHAR_MIN’
  tcsym = lookup_symbol("tcache", 0, VAR_DOMAIN, 0).symbol;
                                     ^~~~~~~~~~
                                     CHAR_MIN
../heap_ptmalloc.cpp:914:10: error: ‘lookup_symbol’ was not declared in this scope
  tcsym = lookup_symbol("tcache", 0, VAR_DOMAIN, 0).symbol;
          ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:919:8: error: ‘value_of_variable’ was not declared in this scope
  val = value_of_variable(tcsym, 0);
        ^~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:920:8: error: ‘value_coerce_to_target’ was not declared in this scope
  val = value_coerce_to_target(val);
        ^~~~~~~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:921:9: error: ‘value_type’ was not declared in this scope
  type = value_type(val);
         ^~~~~~~~~~
../heap_ptmalloc.cpp:921:9: note: suggested alternative: ‘value’
  type = value_type(val);
         ^~~~~~~~~~
         value
../heap_ptmalloc.cpp:922:24: error: ‘TYPE_TARGET_TYPE’ was not declared in this scope
  type = check_typedef (TYPE_TARGET_TYPE (type));
                        ^~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:922:24: note: suggested alternative: ‘__TIME_T_TYPE’
  type = check_typedef (TYPE_TARGET_TYPE (type));
                        ^~~~~~~~~~~~~~~~
                        __TIME_T_TYPE
../heap_ptmalloc.cpp:922:9: error: ‘check_typedef’ was not declared in this scope
  type = check_typedef (TYPE_TARGET_TYPE (type));
         ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:923:10: error: ‘TYPE_LENGTH’ was not declared in this scope
  valsz = TYPE_LENGTH(type);
          ^~~~~~~~~~~
../heap_ptmalloc.cpp:928:9: error: ‘value_as_address’ was not declared in this scope
  addr = value_as_address(val);
         ^~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:928:9: note: suggested alternative: ‘ca_eval_address’
  addr = value_as_address(val);
         ^~~~~~~~~~~~~~~~
         ca_eval_address
../heap_ptmalloc.cpp:929:52: error: invalid use of incomplete type ‘struct thread_info’
  CA_PRINT("tcache for ptid.pid [%d]: 0x%lx\n", info->ptid.pid, addr);
                                                    ^~
../heap_ptmalloc.cpp:902:23: note: forward declaration of ‘struct thread_info’
 thread_tcache (struct thread_info *info, void *data)
                       ^~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘bool build_tcache()’:
../heap_ptmalloc.cpp:962:2: error: ‘ptid_t’ was not declared in this scope
  ptid_t old;
  ^~~~~~
../heap_ptmalloc.cpp:962:2: note: suggested alternative: ‘pid_t’
  ptid_t old;
  ^~~~~~
  pid_t
../heap_ptmalloc.cpp:967:2: error: ‘old’ was not declared in this scope
  old = inferior_ptid;
  ^~~
../heap_ptmalloc.cpp:967:2: note: suggested alternative: ‘void’
  old = inferior_ptid;
  ^~~
  void
../heap_ptmalloc.cpp:967:8: error: ‘inferior_ptid’ was not declared in this scope
  old = inferior_ptid;
        ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:969:2: error: ‘iterate_over_threads’ was not declared in this scope
  iterate_over_threads(thread_tcache, NULL);
  ^~~~~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:972:2: error: ‘switch_to_thread’ was not declared in this scope
  switch_to_thread (old);
  ^~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:972:2: note: suggested alternative: ‘ca_thread’
  switch_to_thread (old);
  ^~~~~~~~~~~~~~~~
  ca_thread
../heap_ptmalloc.cpp: In function ‘bool read_malloc_state_by_symbol(address_t, ca_malloc_state*)’:
../heap_ptmalloc.cpp:989:38: error: ‘VAR_DOMAIN’ was not declared in this scope
  ma = lookup_symbol("main_arena", 0, VAR_DOMAIN, 0).symbol;
                                      ^~~~~~~~~~
../heap_ptmalloc.cpp:989:38: note: suggested alternative: ‘CHAR_MIN’
  ma = lookup_symbol("main_arena", 0, VAR_DOMAIN, 0).symbol;
                                      ^~~~~~~~~~
                                      CHAR_MIN
../heap_ptmalloc.cpp:989:7: error: ‘lookup_symbol’ was not declared in this scope
  ma = lookup_symbol("main_arena", 0, VAR_DOMAIN, 0).symbol;
       ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:994:8: error: ‘value_of_variable’ was not declared in this scope
  val = value_of_variable(ma, 0);
        ^~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:995:12: error: ‘value_type’ was not declared in this scope
  ms_type = value_type(val);
            ^~~~~~~~~~
../heap_ptmalloc.cpp:995:12: note: suggested alternative: ‘ms_type’
  ms_type = value_type(val);
            ^~~~~~~~~~
            ms_type
../heap_ptmalloc.cpp:996:24: error: ‘TYPE_LENGTH’ was not declared in this scope
  mparams.mstate_size = TYPE_LENGTH(ms_type);
                        ^~~~~~~~~~~
../heap_ptmalloc.cpp:998:8: error: ‘value_at’ was not declared in this scope
  val = value_at(ms_type, arena_vaddr);
        ^~~~~~~~
../heap_ptmalloc.cpp:998:8: note: suggested alternative: ‘value’
  val = value_at(ms_type, arena_vaddr);
        ^~~~~~~~
        value
../heap_ptmalloc.cpp:1020:16: warning: invalid conversion from ‘void*’ to ‘mchunkptr {aka malloc_chunk*}’ [-fpermissive]
  mstate->top = (void *)data;
                ^~~~~~~~~~~~
../heap_ptmalloc.cpp:1023:27: warning: invalid conversion from ‘void*’ to ‘mchunkptr {aka malloc_chunk*}’ [-fpermissive]
  mstate->last_remainder = (void *)data;
                           ^~~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘bool read_mp_by_symbol()’:
../heap_ptmalloc.cpp:1391:32: error: ‘VAR_DOMAIN’ was not declared in this scope
  sym = lookup_symbol("mp_", 0, VAR_DOMAIN, 0).symbol;
                                ^~~~~~~~~~
../heap_ptmalloc.cpp:1391:32: note: suggested alternative: ‘CHAR_MIN’
  sym = lookup_symbol("mp_", 0, VAR_DOMAIN, 0).symbol;
                                ^~~~~~~~~~
                                CHAR_MIN
../heap_ptmalloc.cpp:1391:8: error: ‘lookup_symbol’ was not declared in this scope
  sym = lookup_symbol("mp_", 0, VAR_DOMAIN, 0).symbol;
        ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:1396:8: error: ‘value_of_variable’ was not declared in this scope
  val = value_of_variable(sym, 0);
        ^~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp:1440:27: error: ‘value_as_long’ was not declared in this scope
   mparams.MAX_FAST_SIZE = value_as_long(val);
                           ^~~~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘bool in_cache(mchunkptr, size_t)’:
../heap_ptmalloc.cpp:1596:15: warning: invalid conversion from ‘void*’ to ‘malloc_chunk**’ [-fpermissive]
  res = bsearch(&chunkp, g_cached_chunks, g_cached_chunk_count,
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      sizeof(g_cached_chunks[0]), compare_tcache_chunk);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘int type_field_name2no(type*, const char*)’:
../heap_ptmalloc.cpp:2120:9: error: ‘check_typedef’ was not declared in this scope
  type = check_typedef (type);
         ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:2122:18: error: ‘TYPE_NFIELDS’ was not declared in this scope
  for (n = 0; n < TYPE_NFIELDS (type); n++) {
                  ^~~~~~~~~~~~
../heap_ptmalloc.cpp:2123:27: error: ‘TYPE_FIELD_NAME’ was not declared in this scope
   if (strcmp (field_name, TYPE_FIELD_NAME (type, n)) == 0)
                           ^~~~~~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘bool get_field_value(value*, const char*, size_t*, bool)’:
../heap_ptmalloc.cpp:2137:31: error: ‘value_type’ was not declared in this scope
  fieldno = type_field_name2no(value_type(val), fieldname);
                               ^~~~~~~~~~
../heap_ptmalloc.cpp:2137:31: note: suggested alternative: ‘value’
  fieldno = type_field_name2no(value_type(val), fieldname);
                               ^~~~~~~~~~
                               value
../heap_ptmalloc.cpp:2146:14: error: ‘value_field’ was not declared in this scope
  field_val = value_field(val, fieldno);
              ^~~~~~~~~~~
../heap_ptmalloc.cpp:2147:10: error: ‘value_as_long’ was not declared in this scope
  *data = value_as_long(field_val);
          ^~~~~~~~~~~~~
../heap_ptmalloc.cpp: In function ‘bool memcpy_field_value(value*, const char*, char*, size_t)’:
../heap_ptmalloc.cpp:2159:31: error: ‘value_type’ was not declared in this scope
  fieldno = type_field_name2no(value_type(val), fieldname);
                               ^~~~~~~~~~
../heap_ptmalloc.cpp:2159:31: note: suggested alternative: ‘value’
  fieldno = type_field_name2no(value_type(val), fieldname);
                               ^~~~~~~~~~
                               value
../heap_ptmalloc.cpp:2163:14: error: ‘value_field’ was not declared in this scope
  field_val = value_field(val, fieldno);
              ^~~~~~~~~~~
../heap_ptmalloc.cpp:2164:12: error: ‘TYPE_LENGTH’ was not declared in this scope
  fieldsz = TYPE_LENGTH(value_type(field_val));
            ^~~~~~~~~~~
../heap_ptmalloc.cpp:2170:33: error: ‘value_address’ was not declared in this scope
  if (!read_memory_wrapper(NULL, value_address(field_val), buf, fieldsz)) {
                                 ^~~~~~~~~~~~~
../heap_ptmalloc.cpp:2170:33: note: suggested alternative: ‘ca_eval_address’
  if (!read_memory_wrapper(NULL, value_address(field_val), buf, fieldsz)) {
                                 ^~~~~~~~~~~~~
                                 ca_eval_address
../MakeCommon:13: recipe for target 'heap_ptmalloc.o' failed
make: *** [heap_ptmalloc.o] Error 1

**Comment by KennyYanXM** [comment]
this is not an issue, it was my mistake.

**Comment by dshakhov** [comment]
@KennyYanXM, could you please explain what was your mistake?
