### ISSUE TITLE
Argument required (expression to compute). When using heap /u <expr>

### ISSUE THREAD

**Issue by xzxxzx401** [yanqi27/core_analyzer#28]
Environment: Self-complied gdb with core_analyzer, gdb 7.11, Debian9 & 5.4.56.xxx-amd64 (xxx is an inner version).

Version: master, 037f54e

Seems a bug at https://github.com/yanqi27/core_analyzer/blob/037f54ec3429514544c5986cec10a3437f2236d0/src/heap.cpp#L204

`expr` is a pointer to a `myargs`, which is freed at https://github.com/yanqi27/core_analyzer/blob/037f54ec3429514544c5986cec10a3437f2236d0/src/heap.cpp#L216

then we use `expr` at https://github.com/yanqi27/core_analyzer/blob/037f54ec3429514544c5986cec10a3437f2236d0/src/heap.cpp#L258 causing gdb got bad argument. 

Maybe we should copy `expr` and free it after evalute?

**Comment by yanqi27** [comment]
@xzxxzx401 
yes, you are right.

**Comment by yanqi27** [comment]
fixed with https://github.com/yanqi27/core_analyzer/commit/ddede8a87e418e16b5a52915d239c03834d8628a
