### ISSUE TITLE
Glibc 2.13 support

### ISSUE THREAD

**Issue by rahulgopi** [yanqi27/core_analyzer#3]
Hi Michael,
    core_analyzer is not supported for glibc 2.13 version. Could you please let me know how we can add support for glibc 2.13.  IF you can provide support or give us some pointers to add support, much appreciated.

**Comment by yanqi27** [comment]
It shouldn't be difficult. You may look into the following files and compare with glibc's `malloc.c` of version 2.13. I don't have the environment to test and verify and hence didn't include this version.
- src/heap_ptmalloc.h
- src/heap_ptmalloc.cpp

**Comment by rahulgopi** [comment]
Thank you Michael. I looked at the malloc_state in glibc-2.13 and it looks very different.  Adding this fails the copy methods as the struct members are very different from the rest.

#define MALLOC_STATE_MAGIC   0x444c4541l
#define MALLOC_STATE_VERSION (0*0x100l + 1l) /* major*0x100 + minor */

struct malloc_state {
  long          magic;
  long          version;
  mbinptr       av[NAV * 2 + 2];
  char*         sbrk_base;
  int           sbrked_mem_bytes;
  unsigned long trim_threshold;
  unsigned long top_pad;
  unsigned int  n_mmaps_max;
  unsigned long mmap_threshold;
  int           check_action;
  unsigned long max_sbrked_mem;
  unsigned long max_total_mem;
  unsigned int  n_mmaps;
  unsigned int  max_n_mmaps;
  unsigned long mmapped_mem;
  unsigned long max_mmapped_mem;
  int           using_malloc_checking;
};

**Comment by yanqi27** [comment]
Could you try the branch glibc-2.13? I include this glibc version in core analyzer. Let me know if it works for you or not.

**Comment by rahulgopi** [comment]
Thank you very much Michael.   It worked fine on one core.   Another one, failed to obtain &main_arena from gdb.   It complains variable doesnt exist.  I have to look into the core / gdb further ,  again not an issue with core_analyzer. 
 Thank you again for adding support for glibc-2.13.

**Comment by rahulgopi** [comment]
Hi Michael,
    I am trying to decode a core file. When I try to get the & or main_arena or mp_ from gdb, it is not finding the symbol.  I also tried to  attach to the running process and see if the symbol is there, but same result

(gdb) p malloc
$1 = {<text variable, no debug info>} 0x7fe50263d2b0 <malloc>
(gdb) p &main_arena
No symbol "main_arena" in current context.
(gdb) p &mp_
No symbol "mp_" in current context.

binary is not stripped. 
file bcq
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, not stripped

Greatly appreciate any insights.

**Comment by yanqi27** [comment]
@rahulgopi 
Since you get one core file working, you may want to check the environment of the core that doesn't work. `main_arena` and `mp_` are variables in libc.so.

**Comment by yanqi27** [comment]
I will reopen it when user data is available.
