### ISSUE TITLE
[build error] undefined reference to get_pt_malloc_2_35_heap_manager()

### ISSUE THREAD

**Issue by luminais** [yanqi27/core_analyzer#43]
![image](https://user-images.githubusercontent.com/36399225/170807673-67254955-3b29-4a7d-b730-8907fb7e763c.png)
ld error, when I run build_gdb.sh

my environment is:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

**Comment by Celthi** [comment]
are you trying to build the gdb 9.2? Currently, the `build_gdb.sh` is building the gdb 12.1

**Comment by luminais** [comment]
yeap, I'm trying to build gdb 9.2.

![image](https://user-images.githubusercontent.com/36399225/170815350-35cfe9e6-94df-4a63-a325-5835701e11e8.png)
I get the code from branch master:[f9bdd8e](https://github.com/yanqi27/core_analyzer/commit/f9bdd8e084f1383294e7c46b01a6a7affed81e85)
as show in the picture, heap.c in directory gdbplus/gdb-9.2/gdb/ is linked to ../../../src/heap.cpp, which is for gdb 12.1?

Finally, how can I get the code of gdbplus/gdb-9.2 to build for gdb 9.2?

**Comment by Celthi** [comment]
Now the newest master can only build for gdb 12.1. To build gdb 9.2, you can checkout the commit d874db35b15f4ece47960b9dc8c7d41db5a50075
The steps would be
1. Clean up any left build file from your last failing build.
2. git checkout d874db35b15f4ece47960b9dc8c7d41db5a50075
3.  ./build_gdb.sh

**Comment by luminais** [comment]
![image](https://user-images.githubusercontent.com/36399225/170819256-7e1e3315-1314-43ff-a165-fe3cf8e5eacb.png)
get the error!

I get the bin file:gdb/gdb
but there is no command ```heap```
![image](https://user-images.githubusercontent.com/36399225/170819336-f19922b5-680f-4193-81c2-b7207273fa66.png)

 hope some sugesstions for help.

best regards~

**Comment by luminais** [comment]
it works, thanks a lot!

I think there is a need to give a release of gdb 9.2, people like me will be glad for it.

**Comment by Celthi** [comment]
> it works, thanks a lot!
> 
> I think there is a need to give a release of gdb 9.2, people like me will be glad for it.

Recently, we did some refactoring. The gdb 9.2 support will be backed later when we finish the refactoring.
