### ISSUE TITLE
segfault in Core Analyzer

### ISSUE THREAD

**Issue by den818** [yanqi27/core_analyzer#7]
I try to  analyze dump witch was created by gcore. And Core Analyzer  crushed

{   "signal": 11
,   "executable": "/home/korden/core_analyzer-2.17.0/app/Linux/core_analyzer"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 4242143
                ,   "build_id": "d4eced4303dcf56ece60431a2702f7a48a26c422"
                ,   "build_id_offset": 47839
                ,   "function_name": "walk_inuse_blocks(inuse_block*, unsigned long*)"
                ,   "file_name": "/home/korden/core_analyzer-2.17.0/app/Linux/core_analyzer"
                }
              , {   "address": 4228774
                ,   "build_id": "d4eced4303dcf56ece60431a2702f7a48a26c422"
                ,   "build_id_offset": 34470
                ,   "function_name": "build_inuse_heap_blocks(unsigned long*)"
                ,   "file_name": "/home/korden/core_analyzer-2.17.0/app/Linux/core_analyzer"
                }
              , {   "address": 4229154
                ,   "build_id": "d4eced4303dcf56ece60431a2702f7a48a26c422"
                ,   "build_id_offset": 34850
                ,   "function_name": "display_heap_leak_candidates()"
                ,   "file_name": "/home/korden/core_analyzer-2.17.0/app/Linux/core_analyzer"
                }
              , {   "address": 4202550
                ,   "build_id": "d4eced4303dcf56ece60431a2702f7a48a26c422"
                ,   "build_id_offset": 8246
                ,   "function_name": "main"
                ,   "file_name": "/home/korden/core_analyzer-2.17.0/app/Linux/core_analyzer"
                } ]
        } ]
}

#0  0x000000000040badf in walk_inuse_blocks (opBlocks=<value optimized out>, opCount=0x7ffc52656438) at ../heap_ptmalloc.cpp:643
#1  0x00000000004086a6 in build_inuse_heap_blocks (opCount=0x7ffc526564a8) at ../heap.cpp:555
#2  0x0000000000408822 in display_heap_leak_candidates () at ../heap.cpp:1132
#3  0x0000000000402036 in main (argc=<value optimized out>, argv=<value optimized out>) at ../main.cpp:256

(gdb)
638        {
639            struct ca_heap* heap = g_sorted_heaps[heap_index];
640            union ca_malloc_chunk achunk;
641   
642            // For mmap heap, there is only one block and in-use
643            if (heap->mArena->mType == ENUM_HEAP_MMAP_BLOCK)
644            {
645                if (!read_memory_wrapper(NULL, heap->mStartAddr - size_t_sz, &achunk, mchunk_sz))
646                    continue;
647                (*opCount)++;
(gdb) p *heap
$1 = {mArena = 0x7f5f852e9770, mpNext = 0x1f3ecb0, mSegment = 0x7f5fa763da00, mStartAddr = 139714547941416, mEndAddr = 139714550190080, mChunks = 0x0, mNumChunks = 0, mCorrupted = 0, mResearved = 0}
(gdb) p heap->mArena
$2 = (ca_arena *) 0x7f5f852e9770
(gdb) p *(heap->mArena)
Cannot access memory at address 0x7f5f852e9770

**Comment by yanqi27** [comment]
I am not sure why the arena object is invalid. @den818 If it is possible, you can send the core file to me and I should be able to reproduce it locally.

**Comment by yanqi27** [comment]
Close it unless more data is available.
