### ISSUE TITLE
Hi, a question not related to this project but related to your book 'Effective Debugging' 

### ISSUE THREAD

**Issue by lfwin** [yanqi27/core_analyzer#72]
Hi, yan qi

I read the translated version of your book 'Effective Debugging' in this [website](https://celthi.github.io/effective-debugging-zh/chapter_1/01-03dwarf_format.html), I want to know where can I buy original English version book?

many thanks.

**Comment by yanqi27** [comment]
Hi,
It is an unpublished book. If you are interested, you may ask the translator of the aforementioned website for the English version.

**Comment by lfwin** [comment]
I have already written email to ask translator for the book several days ago, but he did not respond to me, so I come here directly to ask for your help. When does your book to publish? Could you please send your book to my email fwinlee@gmail.com? I'll pay you the same as the price of the book.
