### ISSUE TITLE
How to compile gdb (properly) for Debian 9 (codename Stretch)

### ISSUE THREAD

**Issue by amorozov** [yanqi27/core_analyzer#74]
For a number of reason my environment is bound to Debian 9 Stretch.

However I can't (properly) compile core_analyzer's patched gdb for Debian 9:

- the default 12.1 version is compiled but doesn't work because libthread_db installed in the system doesn't match the inferior one
- 7.11.1 doesn't compile because gdb-7.11.1/gdb/segment.h contains C++ template function `ca_read_variable` without any C++ protector, C code including the header obviously fails to compile
- 7.12 (Debian 9 "native" version) also fails to compile due to multiple compilation errors.

Is 7.xx really supported at the moment?

Please suggest

**Comment by yanqi27** [comment]
@amorozov 
I would suggest to use gdb 12.1. The libthread_db issue doesn't seem the debugger issue.
For 7.11.1, it is deprecated in recent core_analyzer release, it might be broken (as you ran into) for the latest commit. If you want to try, I would suggest to use previous release before the change to C++ support.
