### ISSUE TITLE
tcentry's list is too long > 1024

### ISSUE THREAD

**Issue by markwhen** [yanqi27/core_analyzer#8]
Hi, Yan Qi, when i try to use ./core_analyzer-master/bin/Linux/tcmalloc/gdb-7.7/gdb
to analyze my coredump file, and entered gdb, this ERROR occurs:

...
(gdb) heap
tcentry's list is too long > 1024
tcmalloc heap was not initialized successfully
[Error] Failed to walk heap

Is this limit just a arbitrary one, and can I change it?

PS. my coredump file might be generated by a mem leak bug, and the size of it is about 14G (sounds too large).

Thanks!

**Comment by yanqi27** [comment]
@ynsfsmj The heap initializer scan's each list of tcmalloc::CentralFreeList::used_slots_[]. The list shouldn't be longer than sizemap_.num_objects_to_move[cl]. But I hard-coded a limit of 1024. It might be not correct. I haven't found time to fix it. Or the list might be circular which is a symptom of corruption.
You can change the limit to a large number to verify this: in function parse_central_freelist_tcentry() at heap_tcmallo.cpp:924

**Comment by ynsfsmj** [comment]
Thanks a lot!

**Comment by yanqi27** [comment]
It is not an issue.
