### ISSUE TITLE
gdb 13.1 wanted

### ISSUE THREAD

**Issue by fish2bird** [yanqi27/core_analyzer#83]
Hi, Is there a paln for gdb 13.1?

**Comment by yanqi27** [comment]
Thanks for the recommendation. I can discuss it with my partner. Could you give some background on why it is desired instead of  currently available gdb12.1? which platform is it intended?

**Comment by fish2bird** [comment]
> @fish2bird Thanks for the recommendation. I can discuss it with my partner. Could you give some background on why it is desired instead of currently available gdb12.1? which platform is it intended?

Nothing else but gdb 13.1 is newest release since 19 Feb 2023, 😄

**Comment by yanqi27** [comment]
I see. We usually consider the gdb versions come with the mainstream distro like Utuntu's long term supported release. For gdb 13.1, we don't have the plan in the near term.
