### ISSUE TITLE
core_analyser on Redhat 7 with tcmalloc 2.6.1

### ISSUE THREAD

**Issue by pmqs** [yanqi27/core_analyzer#9]
Trying to get core_analyzer running on a 64-bit RedHat 7.2 running with tcmalloc 2.6.1

The standalone core_analyzer doesn't seem to have a makefile for building with tcmalloc support -- is that the case?

Tried building gdb-7.11.1 instead.

Looking in **gdbplus/gdb-7.11.1/gdb** I see two Makefile.in files. assume **Makefile.in.tcmalloc** if for the tcmalloc build.. Used that in the gdb source tree. 

The build for gdb broke here

```
CONFIG_HEADERS=config.h:config.in \
  CONFIG_COMMANDS="default depdir" \
  CONFIG_FILES= \
  CONFIG_LINKS= \
  /bin/sh config.status
./observer.sh h ./doc/observer.texi observer.h
./observer.sh inc ./doc/observer.texi observer.inc
Creating observer.itmp
Creating observer.htmp
make[2]: *** No rule to make target `common/linux-osdata.c', needed by `linux-osdata.o'.  Stop.
```

I got gdb to compile by using the  **gdbplus/gdb-7.11.1/gdb/Makefile.in** and changed all instances of **ptmalloc** to **tcmalloc**.

Next issue was getting the **heap** command to run in gdb.

```
(gdb) heap
Failed to lookup type "TCMalloc_PageMap3<35>::Leaf" and "tcmalloc::Span"
Do you forget to download debug symbol of libtcmalloc?
tcmalloc heap was not initialized successfully
[Error] Failed to walk heap
```

Looks like that message is coming from this section in parse_pagemap.c
 
```
	leaf_type = lookup_transparent_type("TCMalloc_PageMap3<35>::Leaf");
	span_type = lookup_transparent_type("tcmalloc::Span");
	if (leaf_type == NULL || span_type == NULL) {
		CA_PRINT("Failed to lookup type "
		    "\"TCMalloc_PageMap3<35>::Leaf\" and "
		    "\"tcmalloc::Span\"\n");
		CA_PRINT("Do you forget to download debug symbol of "
		    "libtcmalloc?\n");
		return false;
	}
```
When I look for those symbols manually in gdb, I do see `tcmalloc::Span`, but not `TCMalloc_PageMap3<35>::Leaf`

```
(gdb) ptype tcmalloc::Span
type = struct tcmalloc::Span {
    PageID start;
    Length length;
    tcmalloc::Span *next;
    tcmalloc::Span *prev;
    void *objects;
    unsigned int refcount : 16;
    unsigned int sizeclass : 8;
    unsigned int location : 2;
    unsigned int sample : 1;
}

(gdb) ptype TCMalloc_PageMap3<35>::Leaf
No symbol "TCMalloc_PageMap3<35>" in current context.
```
Enclosing the symbol with double quotes seems to make it visible.

```
(gdb) ptype "TCMalloc_PageMap3<35>::Leaf"
type = char [28]
```
Any ideas how to proceed?

**Comment by pmqs** [comment]
Tried running `ptype` on the two symbols before running `heap`  using both my build of gdb and the prebuilt copy- I still get the same result with both.

```
(gdb) ptype "TCMalloc_PageMap3<35>::Leaf"
type = char [28]
(gdb) ptype tcmalloc::Span
type = struct tcmalloc::Span {
    PageID start;
    Length length;
    tcmalloc::Span *next;
    tcmalloc::Span *prev;
    void *objects;
    unsigned int refcount : 16;
    unsigned int sizeclass : 8;
    unsigned int location : 2;
    unsigned int sample : 1;
}
(gdb) heap
Failed to lookup type "TCMalloc_PageMap3<35>::Leaf" and "tcmalloc::Span"
Do you forget to download debug symbol of libtcmalloc?
tcmalloc heap was not initialized successfully
[Error] Failed to walk heap
```


If there is an change that can be made to resolve the symbols, I'm available to test on my setup.

**Comment by yanqi27** [comment]
This should be resolved by https://github.com/yanqi27/core_analyzer/pull/12
