### ISSUE TITLE
How to locate the source code that allocates this memory if a memory leak address is discovered through a heap/leak scan.

### ISSUE THREAD

**Issue by MiloMallo** [yanqi27/core_analyzer#97]
>>> heap /l
Potentially leaked heap memory blocks:
[1] addr=0x556baec53010 size=584
[2] addr=0x556baec53280 size=1000
Total 2 (1KB) leak candidates out of 4 (2KB) in-use memory blocks

**Comment by MiloMallo** [comment]
"heap /l is not very useful  ?

**Comment by yanqi27** [comment]
The `heap /l` command is not designed to return the source code that allocates the leak candidates. You may use other tools, such as Valgrind, to do so.

**Comment by Celthi** [comment]
Core analyzer is not designed to fulfill this goal as it cannot monitor the process runtime behavior. Thus close it.
