### ISSUE TITLE
Adding issue template

### ISSUE THREAD

**Issue by Celthi** [yanqi27/core_analyzer#98]
Let's add one issue template to ask for the following information.
1. OS version
2. Heap manager, version.
3. Lib version
4. Confirm debug symbol loaded.
5. The gdb version.

**Comment by Celthi** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository 
I don't see the setting tab though I have the write permission. 
@yanqi27 could you check it?

**Comment by yanqi27** [comment]
I could see the setting tab. just added.

**Comment by Celthi** [comment]
That's great. Close it.
